# Configuring pandas

In [6]:
# import numpy and pandas
import numpy as np
import pandas as pd

# used for dates
import datetime
from datetime import datetime, date
from sklearn import preprocessing
# Set some pandas options controlling output format
pd.set_option('display.notebook_repr_html', True)
pd.set_option('display.max_columns', 8)
pd.set_option('display.max_rows', 10)
pd.set_option('display.width', 65)

# bring in matplotlib for graphics
import matplotlib.pyplot as plt
%matplotlib inline

# Label Encoding:
The Series does not have to be dtype "category", it can just be dtype "object"

Convert text values to numbers. These can be used in the following situations:

* There are only two values for a column in your data. The values will then become 0/1 - effectively a binary representation
* The values have relationship with each other where comparisons are meaningful (e.g. low<medium<high)

In [2]:
import os
os.getcwd()

'/Users/phoebezhouhuixin/Downloads/Data_Science/pandas'

In [10]:
exam_data = pd.read_csv("../scikit-learn/data/exams.csv", quotechar='"')
exam_data.head()

gender race/ethnicity parental level of education  \
0    male        group E          associate's degree   
1  female        group C          associate's degree   
2    male        group D           bachelor's degree   
3  female        group A           bachelor's degree   
4  female        group D                 high school   

          lunch test preparation course  math score  \
0      standard               completed          79   
1  free/reduced                    none          56   
2      standard                    none          86   
3      standard                    none          68   
4  free/reduced                    none          49   

   reading score  writing score  
0             75             81  
1             65             64  
2             68             74  
3             78             76  
4             68             61

In [11]:
exam_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   gender                       100 non-null    object
 1   race/ethnicity               100 non-null    object
 2   parental level of education  100 non-null    object
 3   lunch                        100 non-null    object
 4   test preparation course      100 non-null    object
 5   math score                   100 non-null    int64 
 6   reading score                100 non-null    int64 
 7   writing score                100 non-null    int64 
dtypes: int64(3), object(5)
memory usage: 6.4+ KB


In [12]:
le = preprocessing.LabelEncoder()
exam_data['gender'] = le.fit_transform(exam_data['gender'].astype(str))
exam_data.head()

gender race/ethnicity parental level of education  \
0       1        group E          associate's degree   
1       0        group C          associate's degree   
2       1        group D           bachelor's degree   
3       0        group A           bachelor's degree   
4       0        group D                 high school   

          lunch test preparation course  math score  \
0      standard               completed          79   
1  free/reduced                    none          56   
2      standard                    none          86   
3      standard                    none          68   
4  free/reduced                    none          49   

   reading score  writing score  
0             75             81  
1             65             64  
2             68             74  
3             78             76  
4             68             61

# One-Hot Encoding
The Series does not have to be dtype "category", it can just be dtype "object"

* Use when there is no meaningful comparison between values in the column
* Creates a new column for each unique value for the specified feature in the data set## One-Hot Encoding:

* Use when there is no meaningful comparison between values in the column
* Creates a new column for each unique value for the specified feature in the data set

## get dummies for a series

In [13]:
pd.get_dummies(exam_data['race/ethnicity']).head()

group A  group B  group C  group D  group E
0        0        0        0        0        1
1        0        0        1        0        0
2        0        0        0        1        0
3        1        0        0        0        0
4        0        0        0        1        0

## get dummies for specified columns of a df

In [8]:
exam_data = pd.get_dummies(exam_data, columns=['race/ethnicity'])
exam_data = pd.get_dummies(exam_data, columns=['parental level of education', 
                                               'lunch', 
                                               'test preparation course'])
exam_data.head()

gender  math score  reading score  writing score  ...  \
0       1          79             75             81  ...   
1       0          56             65             64  ...   
2       1          86             68             74  ...   
3       0          68             78             76  ...   
4       0          49             68             61  ...   

   lunch_free/reduced  lunch_standard  \
0                   0               1   
1                   1               0   
2                   0               1   
3                   0               1   
4                   1               0   

   test preparation course_completed  \
0                                  1   
1                                  0   
2                                  0   
3                                  0   
4                                  0   

   test preparation course_none  
0                             0  
1                             1  
2                             1  
3                             1  
4                             1  

[5 rows x 19 columns]

# Creating Categoricals --> i.e. pandas Series with dtype "category"

## create from list

In [2]:
# create a categorical directly from a list.  
lmh_values = ["low", "high", "medium", "medium", "high"]
lmh_cat = pd.Categorical(lmh_values)
lmh_cat

[low, high, medium, medium, high]
Categories (3, object): [high, low, medium]

In [3]:
# examine the categories
lmh_cat.categories

Index(['high', 'low', 'medium'], dtype='object')

In [4]:
# retreive the values
lmh_cat.get_values()

array(['low', 'high', 'medium', 'medium', 'high'], dtype=object)

In [5]:
# .codes shows the integer mapping for each value of the categorical
lmh_cat.codes

array([1, 0, 2, 2, 0], dtype=int8)

### create from list but explicitly state the order of the categories --> can sort

In [6]:

lmh_cat = pd.Categorical(lmh_values,
                         categories=["low", "medium", "high"])
lmh_cat

[low, high, medium, medium, high]
Categories (3, object): [low, medium, high]

In [7]:
# the codes are...
lmh_cat.codes

array([0, 2, 1, 1, 2], dtype=int8)

In [8]:
# sorting is done using the codes underlying each value
lmh_cat.sort_values()

[low, medium, medium, high, high]
Categories (3, object): [low, medium, high]

## create a categorical using a Series and dtype

In [9]:
cat_series = pd.Series(lmh_values, dtype="category")
cat_series

0       low
1      high
2    medium
3    medium
4      high
dtype: category
Categories (3, object): [high, low, medium]

In [10]:
# create a categorical using .astype()
s = pd.Series(lmh_values)
as_cat = s.astype('category')
cat_series

0       low
1      high
2    medium
3    medium
4      high
dtype: category
Categories (3, object): [high, low, medium]

In [11]:
# a categorical has a .cat property that lets you access info
cat_series.cat

In [12]:
# get the index for the categorical
cat_series.cat.categories

Index(['high', 'low', 'medium'], dtype='object')

# Sort categoricals (without replacing the category names with numbers)

In [16]:
# create an ordered categorical of precious metals
# order is important for determining relative value
metal_values = ["bronze", "gold", "silver", "bronze"]
metal_categories = ["bronze", "silver", "gold"]
metals = pd.Categorical(metal_values,
                        categories=metal_categories,
                        ordered = True)
metals

[bronze, gold, silver, bronze]
Categories (3, object): [bronze < silver < gold]

In [19]:
# codes are the integer value assocaited with each item
metals.codes

array([0, 2, 1, 0], dtype=int8)

In [17]:
# reverse the metals
metals_reversed_values = pd.Categorical(
    metals.get_values()[::-1],
    categories = metals.categories, 
    ordered=True)
metals_reversed_values

[bronze, silver, gold, bronze]
Categories (3, object): [bronze < silver < gold]

In [20]:
# and for metals2
metals_reversed_values.codes

array([0, 1, 2, 0], dtype=int8)

# Compare two categoricals

In [18]:
# compare the two categoricals
metals <= metals_reversed_values

array([ True, False,  True,  True])

In [21]:
# creating a categorical with a non existent category value
pd.Categorical(["bronze", "copper"],
               categories=metal_categories)

[bronze, NaN]
Categories (3, object): [bronze, silver, gold]

# Renaming Categories (which changes the category values as well)

In [22]:
# create a categorical with 3 categories
cat = pd.Categorical(["a","b","c","a"], 
                     categories=["a", "b", "c"])
cat

[a, b, c, a]
Categories (3, object): [a, b, c]

In [23]:
# renames the categories (and also the values)
cat.categories = ["bronze", "silver", "gold"]
cat

[bronze, silver, gold, bronze]
Categories (3, object): [bronze, silver, gold]

In [24]:
# this also renames 
cat.rename_categories(["x", "y", "z"])

[x, y, z, x]
Categories (3, object): [x, y, z]

In [25]:
# the rename is not done in-place
cat

[bronze, silver, gold, bronze]
Categories (3, object): [bronze, silver, gold]

# Appending new categories

In [26]:
# add a new platinum category
with_platinum = metals.add_categories(["platinum"])
with_platinum

[bronze, gold, silver, bronze]
Categories (4, object): [bronze < silver < gold < platinum]

# Removing Categories (and hence category values)

In [27]:
# remove bronze category
no_bronze = metals.remove_categories(["bronze"])
no_bronze

[NaN, gold, silver, NaN]
Categories (2, object): [silver < gold]

# Removing unused categories

In [28]:
# remove any unused categories (in this case, platinum)
with_platinum.remove_unused_categories()

[bronze, gold, silver, bronze]
Categories (3, object): [bronze < silver < gold]

# Setting categories

In [29]:
# sample Series
s = pd.Series(["one","two","four", "five"], dtype="category")
s

0     one
1     two
2    four
3    five
dtype: category
Categories (4, object): [five, four, one, two]

In [30]:
# remove the "two", "three" and "five" categories (replaced with NaN)
s = s.cat.set_categories(["one","four"])
s

0     one
1     NaN
2    four
3     NaN
dtype: category
Categories (2, object): [one, four]

# Describe

In [31]:
# get descriptive info on the metals categorical
metals.describe()

            counts  freqs
categories               
bronze           2   0.50
silver           1   0.25
gold             1   0.25

# Value counts

In [32]:
# count the values in the categorical
metals.value_counts()

bronze    2
silver    1
gold      1
dtype: int64

# Minimum, maximum and mode (of ordered Categorical)

In [33]:
# find the min, max and mode of the metals categorical
(metals.min(), metals.max(), metals.mode())

('bronze', 'gold', [bronze]
 Categories (3, object): [bronze < silver < gold])

# Bin categoricals

In [17]:
# create a DataFrame of 100 values
np.random.seed(123456)
values = np.random.randint(0, 100, 5)
bins = pd.DataFrame({ "Values": values})
bins

Values
0      65
1      49
2      56
3      43
4      43

In [18]:
# cut the values into 
bins['Group'] = pd.cut(values, range(0, 101, 10))
bins

Values     Group
0      65  (60, 70]
1      49  (40, 50]
2      56  (50, 60]
3      43  (40, 50]
4      43  (40, 50]

In [19]:
# examine the categorical that was created
bins.Group

0    (60, 70]
1    (40, 50]
2    (50, 60]
3    (40, 50]
4    (40, 50]
Name: Group, dtype: category
Categories (10, interval[int64]): [(0, 10] < (10, 20] < (20, 30] < (30, 40] ... (60, 70] < (70, 80] < (80, 90] < (90, 100]]

# Append new column with values of corresponding bin group

In [34]:
# 10 students with random grades
np.random.seed(123456)
names = ['Ivana', 'Norris', 'Ruth', 'Lane', 'Skye', 'Sol', 
         'Dylan', 'Katina', 'Alissa', "Marc"]
grades = np.random.randint(50, 101, len(names))
scores = pd.DataFrame({'Name': names, 'Grade': grades})
scores

   Grade    Name
0     51   Ivana
1     92  Norris
2    100    Ruth
3     99    Lane
4     93    Skye
5     97     Sol
6     93   Dylan
7     77  Katina
8     82  Alissa
9     73    Marc

In [35]:
# bins and their mappings to letter grades
score_bins =    [ 0,  59,   62,  66,   69,   72,  76,   79,   82,  
                 86,   89,   92,  99, 100]
letter_grades = ['F', 'D-', 'D', 'D+', 'C-', 'C', 'C+', 'B-', 'B', 
                 'B+', 'A-', 'A', 'A+']

In [36]:
# cut based upon the bins and assign the letter grade
letter_cats = pd.cut(scores.Grade, score_bins, labels=letter_grades) # cut() --> letter_cats is automatically an ordered Categorical 
scores['Letter'] = letter_cats # edits the df in place
scores

   Grade    Name Letter
0     51   Ivana      F
1     92  Norris     A-
2    100    Ruth     A+
3     99    Lane      A
4     93    Skye      A
5     97     Sol      A
6     93   Dylan      A
7     77  Katina     C+
8     82  Alissa     B-
9     73    Marc      C

In [37]:
# examine the underlying categorical
letter_cats

0     F
1    A-
2    A+
3     A
4     A
5     A
6     A
7    C+
8    B-
9     C
Name: Grade, dtype: category
Categories (13, object): [F < D- < D < D+ ... B+ < A- < A < A+]

In [38]:
# how many of each grade occurred?
scores.Letter.value_counts()

A     4
A+    1
A-    1
B-    1
C+    1
     ..
B     0
C-    0
D+    0
D     0
D-    0
Name: Letter, Length: 13, dtype: int64

In [39]:
# and sort by letter grade instead of numeric grade
scores.sort_values(by=['Letter'], ascending=False)

   Grade    Name Letter
2    100    Ruth     A+
6     93   Dylan      A
5     97     Sol      A
4     93    Skye      A
3     99    Lane      A
1     92  Norris     A-
8     82  Alissa     B-
7     77  Katina     C+
9     73    Marc      C
0     51   Ivana      F